// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1ZRnZF6BsAh70RFC8Q5KuJkpNBF3SjTI',
    appId: '1:804215194336:web:6bda058ec20b250175c685',
    messagingSenderId: '804215194336',
    projectId: 'planetsort',
    authDomain: 'planetsort.firebaseapp.com',
    storageBucket: 'planetsort.appspot.com',
    measurementId: 'G-TFLTC476MY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLbXABsLZ6uLZ8kVCWQUQkf2zooXbrYmU',
    appId: '1:804215194336:android:76a7b2b21ab9780475c685',
    messagingSenderId: '804215194336',
    projectId: 'planetsort',
    storageBucket: 'planetsort.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD832_ZHVE7MZn-LdxwB2dBUCKVoNBZ6lU',
    appId: '1:804215194336:ios:2678ad0ea3bd3a5175c685',
    messagingSenderId: '804215194336',
    projectId: 'planetsort',
    storageBucket: 'planetsort.appspot.com',
    iosBundleId: 'com.example.planetsort',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD832_ZHVE7MZn-LdxwB2dBUCKVoNBZ6lU',
    appId: '1:804215194336:ios:003167101ad631d575c685',
    messagingSenderId: '804215194336',
    projectId: 'planetsort',
    storageBucket: 'planetsort.appspot.com',
    iosBundleId: 'com.example.planetsort.RunnerTests',
  );
}
